cookies = {
    'MVID_CITY_ID': 'CityCZ_2534',
    'MVID_GUEST_ID': '19266122230',
    'MVID_REGION_ID': '10',
    'searchType2': '1',
    'MVID_TIMEZONE_OFFSET': '5',
    'MVID_KLADR_ID': '0200000100000',
    'MVID_REGION_SHOP': 'S906',
    'MVID_GEOLOCATION_NEEDED': 'false',
    'MVID_ABC_TEST_WIDGET': '0',
    'MVID_AB_TEST_COMPARE_ONBOARDING': 'true',
    'MVID_ADDRESS_COMMENT_AB_TEST': '2',
    'MVID_BLACK_FRIDAY_ENABLED': 'true',
    'MVID_CALC_BONUS_RUBLES_PROFIT': 'false',
    'MVID_CART_MULTI_DELETE': 'false',
    'MVID_FILTER_TOOLTIP': '1',
    'MVID_IS_NEW_BR_WIDGET': 'true',
    'MVID_LAYOUT_TYPE': '1',
    'MVID_NEW_MBONUS_BLOCK': 'true',
    'MVID_PRICE_FIRST': '2',
    'MVID_PRM20_CMS': 'true',
    'PRESELECT_COURIER_DELIVERY_FOR_KBT': 'true',
    'PROMOLISTING_WITHOUT_STOCK_AB_TEST': '2',
    'MVID_FLOCKTORY_ON': 'true',
    'MVID_NEW_ACCESSORY': 'true',
    'MVID_SERVICES': '111',
    'MVID_SERVICES_DESCRIPTION': 'true',
    '__lhash_': 'a0488e1735f1ba62e4eae675a7eade66',
    'CACHE_INDICATOR': 'false',
    'COMPARISON_INDICATOR': 'false',
    'HINTS_FIO_COOKIE_NAME': '1',
    'JSESSIONID': 'CpGTvqBLLKF33cYZ943j9xX7nJQCL5TGB12jrS72TpnYbLcylmQ0!94126264',
    'MVID_AB_SERVICES_DESCRIPTION': 'var2',
    'MVID_CART_AVAILABILITY': '1',
    'MVID_CATALOG_STATE': '1',
    'MVID_CREDIT_AVAILABILITY': 'true',
    'MVID_FILTER_CODES': 'true',
    'MVID_GET_LOCATION_BY_DADATA': 'DaData',
    'MVID_GTM_DELAY': 'true',
    'MVID_HANDOVER_SUMMARY': 'true',
    'MVID_LP_HANDOVER': '2',
    'MVID_LP_SOLD_VARIANTS': '3',
    'MVID_MCLICK': 'true',
    'MVID_MINI_PDP': 'true',
    'MVID_NEW_DESKTOP_FILTERS': 'true',
    'MVID_NEW_LK': 'true',
    'MVID_NEW_LK_CHECK_CAPTCHA': 'true',
    'MVID_NEW_LK_LOGIN': 'true',
    'MVID_NEW_LK_OTP_TIMER': 'true',
    'MVID_SERVICES_MINI_BLOCK': 'var1',
    'MVID_SMART_BANNER_BOTTOM': 'true',
    'MVID_SUPER_FILTERS': 'false',
    'MVID_TAXI_DELIVERY_INTERVALS_VIEW': 'new',
    'MVID_WEBP_ENABLED': 'true',
    'NEED_REQUIRE_APPLY_DISCOUNT': 'true',
    'bIPs': '-1323973254',
    'flacktory': 'no',
    'MVID_ENVCLOUD': 'prod2',
    'BIGipServeratg-ps-prod_tcp80': '2953108490.20480.0000',
    'Old_Browser_Accept_the_Risk_and_Continue': '1',
}

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0',
    'Accept': 'application/json',
    'Accept-Language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3',
    # 'Accept-Encoding': 'gzip, deflate, br',
    'x-set-application-id': '77c7a513-1a99-4722-bd25-f944d5821d30',
    'Connection': 'keep-alive',
    'Referer': 'https://www.mvideo.ru/noutbuki-planshety-komputery-8/planshety-195/f/skidka=da/tolko-v-nalichii=da',
    # Requests sorts cookies= alphabetically
    # 'Cookie': 'MVID_CITY_ID=CityCZ_2534; MVID_GUEST_ID=19266122230; MVID_REGION_ID=10; searchType2=1; MVID_TIMEZONE_OFFSET=5; MVID_KLADR_ID=0200000100000; MVID_REGION_SHOP=S906; MVID_GEOLOCATION_NEEDED=false; MVID_ABC_TEST_WIDGET=0; MVID_AB_TEST_COMPARE_ONBOARDING=true; MVID_ADDRESS_COMMENT_AB_TEST=2; MVID_BLACK_FRIDAY_ENABLED=true; MVID_CALC_BONUS_RUBLES_PROFIT=false; MVID_CART_MULTI_DELETE=false; MVID_FILTER_TOOLTIP=1; MVID_IS_NEW_BR_WIDGET=true; MVID_LAYOUT_TYPE=1; MVID_NEW_MBONUS_BLOCK=true; MVID_PRICE_FIRST=2; MVID_PRM20_CMS=true; PRESELECT_COURIER_DELIVERY_FOR_KBT=true; PROMOLISTING_WITHOUT_STOCK_AB_TEST=2; MVID_FLOCKTORY_ON=true; MVID_NEW_ACCESSORY=true; MVID_SERVICES=111; MVID_SERVICES_DESCRIPTION=true; __lhash_=a0488e1735f1ba62e4eae675a7eade66; CACHE_INDICATOR=false; COMPARISON_INDICATOR=false; HINTS_FIO_COOKIE_NAME=1; JSESSIONID=CpGTvqBLLKF33cYZ943j9xX7nJQCL5TGB12jrS72TpnYbLcylmQ0!94126264; MVID_AB_SERVICES_DESCRIPTION=var2; MVID_CART_AVAILABILITY=1; MVID_CATALOG_STATE=1; MVID_CREDIT_AVAILABILITY=true; MVID_FILTER_CODES=true; MVID_GET_LOCATION_BY_DADATA=DaData; MVID_GTM_DELAY=true; MVID_HANDOVER_SUMMARY=true; MVID_LP_HANDOVER=2; MVID_LP_SOLD_VARIANTS=3; MVID_MCLICK=true; MVID_MINI_PDP=true; MVID_NEW_DESKTOP_FILTERS=true; MVID_NEW_LK=true; MVID_NEW_LK_CHECK_CAPTCHA=true; MVID_NEW_LK_LOGIN=true; MVID_NEW_LK_OTP_TIMER=true; MVID_SERVICES_MINI_BLOCK=var1; MVID_SMART_BANNER_BOTTOM=true; MVID_SUPER_FILTERS=false; MVID_TAXI_DELIVERY_INTERVALS_VIEW=new; MVID_WEBP_ENABLED=true; NEED_REQUIRE_APPLY_DISCOUNT=true; bIPs=-1323973254; flacktory=no; MVID_ENVCLOUD=prod2; BIGipServeratg-ps-prod_tcp80=2953108490.20480.0000; Old_Browser_Accept_the_Risk_and_Continue=1',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    # Requests doesn't support trailers
    # 'TE': 'trailers',
}

